from dataclasses import dataclass
import math
from typing import List, Any, Dict
from llm_client import chat_with_logprobs

@dataclass
class APICall:
    api_name: str     # e.g. "QA"
    api_input: str    # e.g. 'Where was Joe Biden born?'
    position: int     # Position in the token sequence i (1-based)
    result: str       # r_i, the text returned by the API


def tokenize(text: str) -> List[str]:
    # The actual implementation can be replaced with BPE, this is just a placeholder
    return text.split()

def detokenize(tokens: List[str]) -> str:
    return " ".join(tokens)

def build_weights(n_future: int) -> List[float]:
    """
    The corresponding weighted function in the paper:
    ˜w_t = max(0, 1 - 0.2 * t), and then normalize wt = ˜w_t / sum_s ˜w_s.
    The closer a token is to position i, the greater its weight becomes. 
    """
    raw = [max(0.0, 1.0 - 0.2 * t) for t in range(n_future)]
    s = sum(raw) or 1.0
    return [w / s for w in raw]


def compute_weighted_loss(prefix: str, continuation: str, weights: List[float]) -> float:
    """
    Approximate calculation using the Chat interface with logprobs:
    L_i(z) = - sum_t w_t * log p_M(x_{i+t-1} | z, x_i...x_{i+t-2})
    prefix:  z
    Continuation: Text of x_i..x_n
    weights: The weight w_t corresponding to each target token, with a length equal to the number of continuation tokens
    """
    # 1.  Construct prompt: prefix + prompt the model to continue "generating" continuation
    # Note: This is just for obtaining logprobs, and the model does not need to be allowed to freely operate.
    full_prompt = prefix + continuation

    resp = chat_with_logprobs(full_prompt)
    choice = resp.choices[0]

    # 2.  Roughly align the continuation with the token generated by the model
    # For simplicity, words are separated by spaces; it is actually recommended to use the same tokenizer.
    target_tokens = continuation.split()
    T = len(target_tokens)
    if T == 0:
        return 0.0

    # Assume that choice.logprobs.content[t] corresponds to the t-th token of the generated sequence
    content_logprobs = choice.logprobs.content
    # Only take the first T positions
    content_logprobs = content_logprobs[:T]

    loss = 0.0
    for t, (target, w) in enumerate(zip(target_tokens, weights)):
        if t >= len(content_logprobs):
            # The model hasn't generated enough, let's give it a simple punishment
            loss -= w * math.log(1e-8)
            continue
        
        # A list containing {token, logprob}
        top_lp = content_logprobs[t].top_logprobs
        log_p = None
        for cand in top_lp:
            if cand.token == target:
                log_p = cand.logprob
                break

        # If the target token is not in top_logprobs, it is considered to have an extremely low probability
        if log_p is None:
            log_p = math.log(1e-8)

        loss -= w * log_p

    return loss

def filter_single_api_call(
    x_text: str,
    call: APICall,
    tau_f: float,
) -> bool:
    """
    Calculate L_i^+ and L_i^- for a single API call c_i, and determine whether to retain it:
    Returning True indicates that the condition L_i^- - L_i^+ >= tau_f is met, and the call should be retained.
    """
    # 1.  Split the original text
    x_tokens = tokenize(x_text)
    n = len(x_tokens)
    i = call.position

    # prefix_base = x_1..x_{i-1}，continuation = x_i..x_n
    prefix_base = detokenize(x_tokens[:i-1])
    continuation = detokenize(x_tokens[i-1:])
    n_future = len(continuation.split())
    weights = build_weights(n_future)

    # 2.  Construct three prefixes
    # 2.1 e(c_i, r_i)
    prefix_with = (
        prefix_base
        + f" <API> {call.api_name}({call.api_input}) -> {call.result} </API>"
    )

    # 2.2 ε (empty prefix)
    prefix_empty = ""

    # 2.3 e(c_i, ε)
    prefix_input_only = (
        prefix_base
        + f" <API> {call.api_name}({call.api_input}) </API>"
    )

    # 3. Calculate the weighted loss under three scenarios
    L_plus = compute_weighted_loss(prefix_with, continuation, weights)      # L_i^+
    L_eps = compute_weighted_loss(prefix_empty, continuation, weights)      # L_i(ε)
    L_inp = compute_weighted_loss(prefix_input_only, continuation, weights) # L_i(e(c_i, ε))

    L_minus = min(L_eps, L_inp)   # L_i^- = min(L_i(ε), L_i(e(c_i, ε)))
    diff = L_minus - L_plus       # L_i^- - L_i^+

    # 4. Determine whether to retain
    return diff >= tau_f

def insert_api_with_offset(df):
    """
    Insert the corresponding API content into DataFrame based on the position of x_text
    Parameters:
        df: A DataFrame containing x_text, position, api_name, api_input, and api_result
    Return:
            A DataFrame containing the original x_text and the inserted text
    """
    result_list = []
    grouped = df.groupby('x_text')
    
    for original_text, group in grouped:
        enhanced_text = original_text
        offset = 0
        
        # Sort by position in ascending order (insert from front to back)
        sorted_group = group.sort_values('position', ascending=True)
         
        for idx, row in sorted_group.iterrows():
            pos = row['position'] + offset
            api_name = row['api_name']
            api_input_content = row['api_input']

            if pos < 0 or pos > len(enhanced_text):
                continue
            
            api_text = f'[{api_name}("{api_input_content}")] → {row["api_result"]} '
            enhanced_text = enhanced_text[:pos] + api_text + enhanced_text[pos:]
            offset += len(api_text)

        result_list.append({
            'original_text': original_text,
            'enhanced_text': enhanced_text,
            'api_count': len(group)
        })
    
    return pd.DataFrame(result_list)

def filter_api_calls_for_sample(
    args: argparse.Namespace
) -> List[APICall]:
    """
    Filter all candidate API calls in a sample and return the retained subset. [file:1][web:82]
    x_text: original text
    calls: candidate API calls
    tau_f: threshold, values of 0.5, 1.0, and 2.0 are listed in the paper's table
    """
    df = pd.read_csv(args.file_path, sep='\t')
    df['is_leaf'] = False
    for i, row in df.iterrows():
        x_text = row['x_text']
        api_name = row['api_name']
        api_input = row['api_input']
        result = row['api_result']
        df.loc[i, 'is_leaf'] = filter_single_api_call(
            x_text, 
            APICall(api_name, api_input, -1, result), 
            args.tau_f
        )

    leaf_df = df[df['is_leaf'] == True].reset_index(drop=True)
    leaf_df = insert_api_with_offset(leaf_df)

    if args.output_path:
        leaf_df.to_csv(args.output_path, sep='\t', index=False)

    print(f"Filter result: {leaf_df.shape[0]/df.shape[0]}({leaf_df.shape[0]}/{df.shape[0]})")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--file_path', type=str, action='store_true', help='input file path')
    parser.add_argument('-o', '--output_path', type=str, action='store_true', help='output file path')
    parser.add_argument('-t', '--tau_f', type=float, default=0.5, action='store_true', help='tau_f')

    args = parser.parse_args()

    filter_api_calls_for_sample(args)